server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # compression
  gzip on;
  gzip_vary on;
  gzip_min_length 1024;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  # SPA / single page : tout retombe sur index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # assets hashés (Vite) : cache long et immutable
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
